// File generated by FlutterFire CLI / Firebase integration
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-qZ6xUK3CjkFyhiwrZreFOjjov6DlFNU',
    appId: '1:289271292018:web:9307fcf22220262769a2eb',
    messagingSenderId: '289271292018',
    projectId: 'haandi-web-app',
    authDomain: 'haandi-web-app.firebaseapp.com',
    storageBucket: 'haandi-web-app.firebasestorage.app',
    measurementId: 'G-TMZ50DK781',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmCYTEc2DTVWO9Zgv567wWtEogeYypc7w',
    appId: '1:289271292018:android:dcf254737a48329069a2eb',
    messagingSenderId: '289271292018',
    projectId: 'haandi-web-app',
    storageBucket: 'haandi-web-app.firebasestorage.app',
  );
}
